---
- name: Install NGINX Plus HA keepalived package
  ansible.builtin.package:
    name: nginx-ha-keepalived
    state: present
  when:
    - ansible_facts['os_family'] == 'Alpine'
    - ansible_facts['distribution'] == 'Amazon'
