---
- name: Install NGINX Plus HA keepalived package
  ansible.builtin.package:
    name: nginx-ha-keepalived
    state: present
  when:
    - ansible_facts['os_family'] == 'Alpine'
    - ansible_facts['distribution'] == 'Amazon'

- name: Configure NGINX Plus keepalived HA
  ansible.builtin.template:
    src: keepalived/keepalived.conf.tmpl.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  when:
    - ansible_facts['os_family'] == 'Alpine'
    - ansible_facts['distribution'] == 'Amazon'
