---
- include_tasks: "{{ role_path }}/tasks/modules/install-njs.yml"
  when: nginx_modules.njs | default(false)

- include_tasks: "{{ role_path }}/tasks/modules/install-perl.yml"
  when: nginx_modules.perl | default(false)

- include_tasks: "{{ role_path }}/tasks/modules/install-geoip.yml"
  when:
    - nginx_modules.geoip | default(false)
    - ansible_os_family != "RedHat"
    - ansible_distribution_major_version != "8"

- include_tasks: "{{ role_path }}/tasks/modules/install-image-filter.yml"
  when: nginx_modules.image_filter | default(false)

- include_tasks: "{{ role_path }}/tasks/modules/install-rtmp.yml"
  when:
    - nginx_modules.rtmp | default(false)
    - nginx_type == "plus"

- include_tasks: "{{ role_path }}/tasks/modules/install-xslt.yml"
  when: nginx_modules.xslt | default(false)

- include_tasks: "{{ role_path }}/tasks/modules/install-waf.yml"
  when:
    - nginx_modules.waf | default(false)
    - nginx_type == "plus"
