---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos-6
    image: centos:6
    dockerfile: ../common/Dockerfile.j2
  - name: centos-7
    image: centos:7
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
  - name: centos-8
    image: centos:8
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: ../common/playbook_source.yml
verifier:
  name: testinfra
  directory: ../common/test_source
scenario:
  name: source_centos
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
