---
- name: Prepare
  hosts: all
  gather_facts: true

  tasks:

    - name: "Install Python el7+"
      package:
        name:
          - python3
          - python3-pip
          - python3-devel
        state: present

    - name: "Set Python3 as default el8"
      alternatives:
        name: python
        path: /usr/bin/python3
        link: /usr/bin/python
      when: ansible_distribution_major_version == "8"

    - name: "Install Build Tools"
      package:
        name:
          - "@Development tools"
          - gcc
          - glibc
          - glibc-common
          - gd
          - gd-devel
          - perl-core
          - wget
          - ca-certificates
          - zlib-devel
        state: present

    - name: "Add nginx user"
      user:
        name: nginx
