---
- name: Prepare
  hosts: all
  gather_facts: true

  tasks:

    - name: "Install Python el7+"
      package:
        name:
          - python3
          - python3-pip
          - python3-devel
        state: present

    - name: "Install Build Tools"
      package:
        name:
          - "@Development tools"
          - gcc
          - glibc
          - glibc-common
          - gd
          - gd-devel
          - perl-core
          - wget
          - ca-certificates
        state: present

    - name: "Add nginx user"
      user:
        name: nginx
