---
- name: Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: "Install python for Ansible"
      raw: "(test -e /usr/bin/python || test -e /usr/bin/python3) ||\
        (dnf install -y epel-release && dnf -y update && dnf install -y python3)"
      changed_when: "'Installed' in update_result.stdout"
      register: update_result
      retries: 10
      delay: 5
      until: update_result.rc == 0

    - name: "Install SCL el6"
      package:
        name:
          - centos-release-scl
        state: present
      when: ansible_distribution_major_version == "6"

    - name: "Install Python el6"
      package:
        name:
          - rh-python36
          - rh-python36-python-pip
          - rh-python36-python-devel
        state: present
      when: ansible_distribution_major_version == "6"

    - name: "Install Python el7+"
      package:
        name:
          - python3
          - python3-pip
          - python3-devel
        state: present
      when: ansible_distribution_major_version >= "7"

    - name: "Install Build Tools"
      package:
        name:
          - "@Development tools"
          - gcc
          - glibc
          - glibc-common
          - gd
          - gd-devel
          - perl-core
          - zlib-devel
        state: present
