---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: debian-stretch
    image: python:3.7-stretch
    dockerfile: ../common/Dockerfile.j2
  - name: debian-buster
    image: python:buster
    dockerfile: ../common/Dockerfile.j2
  # - name: ubuntu-xenial
  #   image: ubuntu:xenial
  #   dockerfile: ../common/Dockerfile.j2
  # - name: ubuntu-bionic
  #   image: ubuntu:bionic
  #   dockerfile: ../common/Dockerfile.j2
provisioner:
  name: ansible
  playbooks:
    converge: ../common/playbook_source.yml
verifier:
  name: testinfra
  directory: ../common/test_source
