---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: "Add backports repo for Buster"
      apt_repository:
        repo: deb http://ftp.us.debian.org/debian buster-backports main
      when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"

    - name: "Install Build Tools"
      apt:
        name:
          - build-essential
          - perl
          - tar
          - checkinstall
          - zlib1g-dev
          - libtemplate-perl
        state: present

    - name: Install python for Ansible
      raw: (test -e /usr/bin/python || test -e /usr/bin/python3) || (apt install -y python-minimal)
      changed_when: "'installed' in update_result.stdout"
      register: update_result
      retries: 10
      delay: 5
      until: update_result.rc == 0
