---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "implement-dependabot"
  - package-ecosystem: "pip"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    target-branch: "implement-dependabot"
