---
sudo: required
language: python
services:
  - docker
env:
  - scenario: default
  - scenario: default_alpine
  - scenario: default_centos
  - scenario: module
  - scenario: module_alpine
  - scenario: module_centos
  - scenario: stable_push
  - scenario: stable_push_alpine
  - scenario: stable_push_centos
  - scenario: template
  - scenario: template_alpine
  - scenario: template_centos
  - scenario: unit
  - scenario: unit_alpine
  - scenario: unit_centos
before_install:
  - sudo apt-get -qq update
install:
  - python3 pip install ansible==2.9.6
  - python3 pip install molecule[docker]>=3.0.0
  - python3 pip install ansible-lint
  - python3 pip install flake8
script:
  - travis_wait 50 molecule test -s $scenario
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
