---
sudo: required
language: python
services:
  - docker
env:
  - scenario: default
  - scenario: module
  - scenario: stable_push
  - scenario: template
  - scenario: unit
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule[docker]
script:
  - travis_wait 50 molecule test -s $scenario --parallel
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
