---
sudo: required
language: python
services:
  - docker
env:
  - scenario: default
  - scenario: default_alpine
  - scenario: default_centos
  - scenario: module
  - scenario: module_alpine
  - scenario: module_centos
  - scenario: stable_push
  - scenario: stable_push_alpine
  - scenario: stable_push_centos
  - scenario: template
  - scenario: template_alpine
  - scenario: template_centos
  - scenario: unit
  - scenario: unit_alpine
  - scenario: unit_centos
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible==2.9.4
  - pip install molecule[docker]==2.22
script:
  - travis_wait 50 molecule test -s $scenario
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
