---
language: python
services: docker
jobs:
  include:
    - name: "(Debian/Ubuntu) Install Specific Version"
      env:
        scenario: default
    - name: "(Alpine) Install Specific Version"
      env:
        scenario: default_alpine
    - name: "(CentOS) Install Specific Version"
      env:
        scenario: default_centos
    - name: "(Debian/Ubuntu) Install Modules"
      env:
        scenario: module
    - name: "(Alpine) Install Modules"
      env:
        scenario: module_alpine
    - name: "(CentOS) Install Modules"
      env:
        scenario: module_centos
    - name: "(Debian/Ubuntu) Install Stable Branch and Push Configuration"
      env:
        scenario: stable_push
    - name: "(Alpine) Install Stable Branch and Push Configuration"
      env:
        scenario: stable_push_alpine
    - name: "(CentOS) Install Stable Branch and Push Configuration"
      env:
        scenario: stable_push_centos
    - name: "(Debian/Ubuntu) Use Template Setting"
      env:
        scenario: template
    - name: "(Alpine) Use Template Setting"
      env:
        scenario: template_alpine
    - name: "(CentOS) Use Template Setting"
      env:
        scenario: template_centos
    - name: "(Debian/Ubuntu) Install NGINX Unit"
      env:
        scenario: unit
    - name: "(Alpine) Install NGINX Unit"
      env:
        scenario: unit_alpine
    - name: "(CentOS) Install NGINX Unit"
      env:
        scenario: unit_centos
    - name: "(Debian/Ubuntu) Install from Source"
      env:
        scenario: source
    - name: "(Alpine) Install from Source"
      env:
        scenario: source_alpine
    - name: "(CentOS) Install from Source"
      env:
        scenario: source_centos
before_install: sudo apt-get -qq update
install:
  - pip install ansible==2.9.12
  - pip install molecule==3.0.6
  - pip install docker==4.2.2
  - pip install ansible-lint==4.3.0
script:
  - molecule --version
  - ansible --version
  - travis_wait 50 molecule test -s $scenario
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
