---
driver:
  name: docker
platforms:
  # - name: almalinux-8
  #   image: almalinux:8
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /usr/sbin/init
  # - name: almalinux-9
  #   image: almalinux:9
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /usr/sbin/init
  - name: amazonlinux-2
    image: amazonlinux:2
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: debian-bullseye
    image: debian:bullseye-slim
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
  # - name: oraclelinux-8
  #   image: oraclelinux:8
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /usr/sbin/init
  # - name: oraclelinux-9
  #   image: oraclelinux:9
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /usr/sbin/init
  # - name: rhel-8
  #   image: redhat/ubi8:8.7
  #   # platform: s390x
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /usr/sbin/init
  - name: rhel-9
    image: redhat/ubi9:9.1.0
    # platform: aarch64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  # - name: rockylinux-8
  #   image: rockylinux:8
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /usr/sbin/init
  # - name: rockylinux-9
  #   image: rockylinux:9.0
  #   dockerfile: ../common/Dockerfile.j2
  #   privileged: true
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   command: /usr/sbin/init
  - name: ubuntu-focal
    image: ubuntu:focal
    # platform: s390x
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
  - name: ubuntu-jammy
    image: ubuntu:jammy
    # platform: aarch64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
provisioner:
  name: ansible
  log: true
  playbooks:
    cleanup: cleanup.yml
    converge: converge.yml
    verify: verify.yml
