---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-nginx
  vars:
    nginx_debug_output: true

    nginx_branch: stable
    nginx_cleanup_config: true
    nginx_cleanup_config_path:
      - directory:
          - /etc/nginx/conf.d
        recurse: false

    nginx_main_upload_enable: true
    nginx_main_upload_src: files/nginx.conf
