---
- name: Converge
  hosts: all
  pre_tasks:
    - name: "Set repo if Alpine"
      set_fact:
        version: "=1.17.6-r1"
      when: ansible_os_family == "Alpine"
    - name: "Install build tools for Alpine"
      apk:
        name: alpine-sdk, perl, linux-headers
        state: present
      become: yes
      when: ansible_os_family == "Alpine"
    - name: "Set repo if Debian"
      set_fact:
        version: "=1.17.6-1~{{ ansible_distribution_release }}"
      when: ansible_os_family == "Debian"
    - name: "Install build tools for Debian"
      apt:
        name:
          - build-essential
          - perl
        state: present
      become: yes
      when: ansible_os_family == "Debian"
    - name: "Set repo if RedHat"
      set_fact:
        version: "-1.17.6-1.el{{ ansible_distribution_major_version }}.ngx"
      when: ansible_os_family == "RedHat"
    - name: "Install build tools for RedHat"
      yum:
        name:
          - "@Development tools"
          - perl
        state: present
      become: yes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == 7
    - name: "Install build tools for RedHat 8"
      dnf:
        name: 
          - "@Development tools"
          - perl
        state: present
      become: yes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == 8
  roles:
    - role: ansible-role-nginx
  vars:
    nginx_version: "{{ version }}"
    nginx_install_from: source
    nginx_branch: mainline
