---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-nginx
  vars:
    nginx_debug_output: true

    nginx_service_modify: true
    nginx_service_timeout: 95
    nginx_selinux: true
    nginx_selinux_tcp_ports:
      - 80
      - 443

    nginx_cleanup_config: true
    nginx_cleanup_config_path:
      - directory:
          - /etc/nginx/conf.d
        recurse: false

    nginx_modules:
      njs: true
      perl: true
      waf: false
      geoip: true
      image_filter: true
      rtmp: true
      xslt: true
