---
collections:
  - name: ansible.posix
    version: 2.2.0
  - name: community.general
    version: 11.4.1
  - name: community.crypto
    version: 2.26.9
  - name: community.docker
    version: 5.2.1
