---
collections:
  - name: ansible.posix
    version: 1.6.1
  - name: community.general
    version: 9.5.0
  - name: community.crypto
    version: 2.22.2
  - name: community.docker
    version: 4.0.0
