---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.0.2
  - name: community.crypto # Only required if you plan to install NGINX Plus
    version: 2.16.0
  - name: community.docker # Only required if you plan to use Molecule
    version: 3.4.11
