---
- name: "(Handler) Check NGINX"
  command: "nginx -t"
  register: config
  ignore_errors: yes
  listen: "(Handler) Run NGINX"

- name: "(Handler) Print NGINX error if syntax check fails"
  fail:
    msg: "{{ config.stderr }}"
  when: config.rc != 0
  listen: "(Handler) Run NGINX"

- name: "(Handler) Systemd daemon-reload"
  systemd:
    daemon_reload: yes

- name: "(Handler) Start/Reload NGINX"
  service:
    name: nginx
    state: reloaded
    enabled: yes
  when:
    - nginx_start | bool
    - not ansible_check_mode | bool
  listen: "(Handler) Run NGINX"

- name: "(Handler) Start NGINX Amplify agent"
  service:
    name: amplify-agent
    state: started

- name: "(Handler: Debian/Ubuntu/CentOS/RedHat) Start NGINX Unit"
  service:
    name: unit
    state: started
    enabled: yes

- name: "(Handler: FreeBSD) Start NGINX Unit"
  service:
    name: unitd
    state: started
    enabled: yes

- name: "(Handler) Run logrotate"
  command: logrotate -f /etc/logrotate.d/nginx
