---
- name: (Handler) Systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: (Handler) Start/reload NGINX
  service:
    name: nginx
    state: reloaded
    enabled: yes
  when:
    - nginx_start | bool
    - not ansible_check_mode | bool
  listen: (Handler) Run NGINX

- name: (Handler) Check NGINX
  command: nginx -t
  register: config
  ignore_errors: yes
  changed_when: false
  listen: (Handler) Run NGINX

- name: (Handler) Print NGINX error if syntax check fails
  debug:
    var: config.stderr_lines
  failed_when: config.rc != 0
  when: config.rc != 0
  listen: (Handler) Run NGINX

- name: (Handler) Start NGINX Amplify agent
  service:
    name: amplify-agent
    state: started

- name: (DEPRECATED Handler - Debian/Ubuntu/CentOS/RedHat) Start NGINX Unit
  service:
    name: unit
    state: started
    enabled: yes

- name: (DEPRECATED Handler - FreeBSD) Start NGINX Unit
  service:
    name: unitd
    state: started
    enabled: yes

- name: (Handler) Run logrotate
  command: logrotate -f /etc/logrotate.d/nginx
