---
- name: Manage NGINX Agent repository
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/agent/setup-{{ ansible_facts['os_family'] | lower }}.yml"
  when: ansible_facts['os_family'] in ['Alpine', 'Debian', 'RedHat', 'Suse']

- name: Install NGINX Agent
  ansible.builtin.package:
    name: nginx-agent
    state: present

- name: Configure NGINX Agent
  ansible.builtin.template:
    src: nginx-agent/nginx-agent.conf.j2
    dest: /etc/nginx-agent/nginx-agent.conf
    mode: "0644"
    backup: true
  when: nginx_agent_configure | bool
  notify: (Handler) Start NGINX Agent
