---
- name: Configure NGINX Agent repository
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/agent/setup-{{ ansible_facts['os_family'] | lower }}.yml"
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: Install NGINX Agent
  ansible.builtin.package:
    name: nginx-agent
    state: present
  notify: (Handler) Start/reloaded NGINX Agent

- name: Configure NGINX Agent with NGINX Management Suite
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/agent/config-nms.yml"
  when: nms_server_host is defined