---
- name: (SLES) Add NGINX Agent repository
  community.general.zypper_repository:
    name: nginx-agent
    repo: https://packages.nginx.org/nginx-agent/sles/$releasever_major
    disable_gpg_check: true # temporary workaround for key mismatch
