---
- name: (AlmaLinux/Amazon Linux/CentOS/Oracle Linux/RHEL/Rocky Linux) Add NGINX Agent repository
  ansible.builtin.yum_repository:
    name: nginx-agent
    file: nginx-agent
    baseurl: https://packages.nginx.org/nginx-agent/{{ (ansible_facts['distribution'] == 'Amazon') | ternary('amzn2', 'centos') }}/$releasever/$basearch/
    description: NGINX Agent
    enabled: true
    gpgcheck: true
    gpgkey: https://nginx.org/keys/nginx_signing.key
    module_hotfixes: true
    mode: "0644"
