---
- name: "(Setup: FreeBSD) Install Required Dependencies"
  block:

    - name: "(Setup: FreeBSD) Install Extra Package(s)"
      pkgng:
        name: "{{ nginx_freebsd_extra_packages }}"
        state: present
      when: nginx_bsd_install_packages|bool

    - name: "(Setup: FreeBSD) Install Extra Port(s)"
      portinstall:
        name: "{{ item }}"
        use_packages: "{{ nginx_bsd_portinstall_use_packages | default(omit) }}"
        state: present
      loop: "{{ nginx_freebsd_extra_packages }}"
      when: not nginx_bsd_install_packages|bool
