---
- include_tasks: "{{ role_path }}/tasks/unit/setup-{{ ansible_os_family | lower }}.yml"
  when:
    - ansible_os_family == "Debian"
      or ansible_os_family == "RedHat"
      or ansible_os_family == "FreeBSD"

- name: "(Install: Debian/Ubuntu/CentOS/RedHat) Install NGINX Unit"
  package:
    name: unit
    state: present
  when: ansible_os_family != "FreeBSD"
  notify: "(Handler: Debian/Ubuntu/CentOS/RedHat) Start NGINX Unit"

- name: "(Install: FreeBSD) Install NGINX Unit"
  portinstall:
    name: unit
    state: present
  when: ansible_os_family == "FreeBSD"
  notify: "(Handler: FreeBSD) Start NGINX Unit"

- include_tasks: "{{ role_path }}/tasks/unit/install-modules.yml"
  when: nginx_unit_modules is defined and nginx_unit_modules
