---
- name: (Amazon Linux) Enable the NGINX Amazon extras package repository
  ansible.builtin.command:
    cmd: amazon-linux-extras enable nginx1
    creates: /usr/sbin/nginx
  when:
    - ansible_facts['distribution'] == 'Amazon'
    - ansible_facts['distribution_major_version'] is version('2', '==')

- name: "{{ nginx_setup | capitalize }} NGINX from the distribution's package repository"
  ansible.builtin.package:
    name: "{{ nginx_distribution_package_name | default('nginx' + (nginx_version | default('') | string)) }}"
    state: "{{ nginx_state }}"
  notify: (Handler) Run NGINX
