---
- name: (Debian/Ubuntu) Configure NGINX repository
  apt_repository:
    filename: nginx
    repo: "{{ item }}"
    update_cache: true
    mode: 0644
  loop: "{{ nginx_repository | default(nginx_default_repository_debian) }}"
  when: nginx_manage_repo | bool

- name: (Debian/Ubuntu) Pin NGINX repository
  blockinfile:
    path: /etc/apt/preferences.d/99nginx
    create: true
    block: |
      Package: *
      Pin: origin nginx.org
      Pin: release o=nginx
      Pin-Priority: 900
    mode: 0644
  when: nginx_repository is not defined

- name: (Debian/Ubuntu) Install NGINX
  apt:
    name: "nginx{{ nginx_version | default('') }}"
    state: "{{ nginx_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  notify: (Handler) Run NGINX
