---
- name: "(Install: Debian/Ubuntu/CentOS/RedHat/FreeBSD) Install NGINX"
  block:

    - import_tasks: setup-debian.yml
      when: ansible_os_family == "Debian"

    - import_tasks: setup-redhat.yml
      when: ansible_os_family == "RedHat"

    - import_tasks: setup-suse.yml
      when: ansible_os_family == "Suse"

    - import_tasks: setup-freebsd.yml
      when: ansible_os_family == "FreeBSD"

    - name: "(Install: Debian/Ubuntu/CentOS/RedHat) Install NGINX"
      import_tasks: install-linux.yml
      when: ansible_os_family != "FreeBSD"

    - name: "(Install: FreeBSD) Install NGINX"
      import_tasks: install-freebsd.yml
      when: ansible_os_family == "FreeBSD"

  when: nginx_install_from == "nginx_repository"

- name: "(Install: Debian/Ubuntu/CentOS/RedHat/FreeBSD) Install NGINX"
  block:

    - name: "(Install: Debian/Ubuntu/CentOS/RedHat) Install NGINX"
      import_tasks: install-linux.yml
      when: ansible_os_family != "FreeBSD"

    - name: "(Install: FreeBSD) Install NGINX"
      import_tasks: install-freebsd.yml
      when: ansible_os_family == "FreeBSD"

  when: nginx_install_from == "os_repository"
