---
- name: "(Install: OSS Linux)"
  include_tasks: "{{ role_path }}/tasks/opensource/install-oss-linux.yml"
  when: ansible_os_family in nginx_linux_families

- name: "(Install: OSS BSD)"
  include_tasks: "{{ role_path }}/tasks/opensource/install-oss-bsd.yml"
  when: ansible_system in nginx_bsd_systems
