---
- name: "{{ nginx_setup | capitalize }} NGINX from the distribution's package repository"
  ansible.builtin.package:
    name: "{{ nginx_distribution_package | default('nginx' + (nginx_version | default(''))) }}"
    state: "{{ nginx_state }}"
  notify: (Handler) Run NGINX
