---
- name: "(Setup: All OSs) Find NGINX Configuration Files"
  find:
    paths: "{{ item.directory }}"
    patterns: "*.conf"
    recurse: "{{ item.recurse | default(false) }}"
  loop: "{{ nginx_cleanup_config_path }}"
  register: nginx_config_files

- name: "(Setup: All OSs) Remove NGINX Configuration Files"
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ nginx_config_files.results | map(attribute='files') | sum(start=[]) | map(attribute='path') | list }}"
