---
- name: "(Setup: All OSs) Set NGINX Plus License State"
  set_fact:
    nginx_license_status: absent

- name: "(Setup: All OSs Besides Alpine Linux) Delete NGINX Plus License"
  file:
    path: /etc/ssl/nginx
    state: absent
  when: ansible_distribution != "Alpine"

- name: "(Setup: Alpine Linux) Delete NGINX Plus License"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apk/cert.key
    - /etc/apk/cert.pem
  when: ansible_distribution == "Alpine"

- include_tasks: "{{ role_path }}/tasks/plus/setup-{{ ansible_os_family | lower }}.yml"
  when:
    - ansible_os_family == "Alpine"
      or ansible_os_family == "FreeBSD"
      or ansible_os_family == "Debian"
      or ansible_os_family == "RedHat"
      or ansible_os_family == "Suse"
