---
- name: Set NGINX Plus repository
  set_fact:
    repository: "{{ nginx_repository |
                default(nginx_plus_default_repository[(ansible_facts['distribution'] == 'Amazon') | ternary('amazon', ansible_facts['os_family'] | lower)]) }}"

- name: Install NGINX from repository
  include_tasks: "{{ role_path }}/tasks/plus/install-{{ ansible_facts['os_family'] | lower }}.yml"
