---
- include_tasks: "{{ role_path }}/tasks/plus/setup-{{ ansible_os_family | lower }}.yml"
  when:
    - ansible_os_family == "Alpine"
      or ansible_os_family == "Debian"
      or ansible_os_family == "RedHat"
      or ansible_os_family == "Suse"

- name: "(Install: Linux) Modify Service for Systemd"
  include_tasks: "{{ role_path }}/tasks/prerequisites/setup-systemd.yml"
  when:
    - ansible_service_mgr == "systemd"
    - nginx_service_modify

- name: "(Install: Linux) Install NGINX Plus"
  package:
    name: "nginx-plus{{ nginx_version | default('') }}"
    state: "{{ nginx_state }}"
  notify: "(Handler: All OSs) Start NGINX"
