---
- name: "(Install: All OSs) Setup license"
  include_tasks: "{{ role_path }}/tasks/plus/setup-license.yml"

- name: "(Install: Linux) Install NGINX Plus"
  include_tasks: "{{ role_path }}/tasks/plus/install-plus-linux.yml"
  when: ansible_os_family in nginx_plus_linux_families

- name: "(Install: FreeBSD) Install NGINX Plus"
  include_tasks: "{{ role_path }}/tasks/plus/install-plus-bsd.yml"
  when: ansible_system in nginx_plus_bsd_systems
