---
- name: "(Install: Plus) Setup license"
  import_tasks: setup-license.yml

- name: "(Install: Plus) Linux"
  import_tasks: install-plus-linux.yml
  when: ansible_os_family in nginx_plus_linux_families

- name: "(Install: Plus) BSD"
  import_tasks: install-plus-bsd.yml
  when: ansible_system in nginx_plus_bsd_systems
