---
- name: (Alpine Linux) Configure NGINX Plus repository
  lineinfile:
    path: /etc/apk/repositories
    insertafter: EOF
    line: "{{ repository }}"
    state: "{{ nginx_license_status | default ('present') }}"

- name: (Alpine Linux) Install NGINX Plus
  apk:
    name: "nginx-plus{{ nginx_version | default('') }}"
    repository: "{{ repository }}"
    state: "{{ nginx_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  notify: (Handler) Run NGINX
