---
- name: "(Install: SUSE) Combine NGINX Plus Certificate and License Keys"
  assemble:
    src: "{{ nginx_conf_dir }}/ssl/nginx"
    dest: "{{ nginx_conf_dir }}/ssl/nginx/nginx-repo-bundle.crt"

- name: "(Install: SUSE) Add NGINX Plus Repository"
  zypper_repository:
    name: nginx-plus
    repo: "https://plus-pkgs.nginx.com/sles/12?ssl_clientcert={{ nginx_conf_dir }}/ssl/nginx/nginx-repo-bundle.crt&ssl_verify=host"
