---
- name: "(All OSs) Create SSL Directory"
  file:
    path: "{{ nginx_conf_dir }}/ssl/nginx"
    state: directory

- name: "(All OSs) Copy NGINX Plus Certificate and License Key"
  copy:
    src: "{{ item }}"
    dest: "{{ nginx_conf_dir }}/ssl/nginx"
    decrypt: yes
  with_items:
    - "{{ nginx_license.certificate }}"
    - "{{ nginx_license.key }}"
