---
name: Molecule CI/CD
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags-ignore: ["**"]
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
permissions: read-all
jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set up Python 3
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.x

      - name: Install Ansible core and Ansible Lint
        run: pip3 install -r .github/workflows/requirements/requirements_ansible_lint.txt

      - name: Install Ansible core collection dependencies
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_collections.yml

      - name: Run Ansible Lint
        run: ansible-lint --force-color

  molecule:
    name: Molecule
    runs-on: ubuntu-24.04
    needs: ansible-lint
    env:
      AGENT_DATA_PLANE_KEY: ${{ secrets.AGENT_DATA_PLANE_KEY }}
      AMPLIFY_API_KEY: ${{ secrets.AMPLIFY_API_KEY }}
      AMPLIFY_EMAIL: ${{ secrets.AMPLIFY_EMAIL }}
      AMPLIFY_PASSWORD: ${{ secrets.AMPLIFY_PASSWORD }}
      NGINX_CRT: ${{ secrets.NGINX_CRT }}
      NGINX_KEY: ${{ secrets.NGINX_KEY }}
      ONE_API_TOKEN: ${{ secrets.ONE_API_TOKEN }}
      ONE_TENANT: ${{ secrets.ONE_TENANT }}
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - agent
          - amplify
          - default
          - distribution
          - downgrade
          - downgrade-plus
          - plus
          - source
          - source-version
          - stable
          - uninstall
          - uninstall-plus
          - upgrade
          - upgrade-plus
          - version
    steps:
      - name: Check out the codebase
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set up Python 3
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.x

      - name: Install Ansible core and Molecule
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        run: pip3 install -r .github/workflows/requirements/requirements_molecule.txt

      - name: Install Ansible core collection dependencies
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_collections.yml

      - name: Run Molecule tests
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
